apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-cluster
  region: ap-northeast-2 
  version: "1.29"

vpc:
  subnets:
    private:
      ap-northeast-2a:
        id: subnet-0a461e01eb561bed9
      ap-northeast-2b:
        id: subnet-0b9b91e4f6a0af846

fargateProfiles:
  - name: app-fargate-profile
    selectors:
      - namespace: app
        labels:
          app: order
    podExecutionRoleARN: arn:aws:iam::702661606257:role/fargatePodExecutionRole

managedNodeGroups:
  - name: app-nodegroup
    minSize: 2
    desiredCapacity: 2
    maxSize: 10
    labels:
      type: app
    instanceType: t3.large
    instanceName: app-node
    privateNetworking: true
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        externalDNS: true
        certManager: true
        appMesh: true
        appMeshPreview: true
        ebs: true
        fsx: true
        efs: true
        awsLoadBalancerController: true
        xRay: true
        cloudWatch: true
  - name: addon-nodegroup
    minSize: 2
    desiredCapacity: 2
    maxSize: 10
    labels:
      type: addon
    instanceType: t3.medium
    instanceName: addon-node
    privateNetworking: true
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        externalDNS: true
        certManager: true
        appMesh: true
        appMeshPreview: true
        ebs: true
        fsx: true
        efs: true
        awsLoadBalancerController: true
        xRay: true
        cloudWatch: true

cloudWatch:
  clusterLogging:
    enableTypes: ["*"]

iam:
  withOIDC: true
  serviceAccounts:
    - metadata:
        name: aws-load-balancer-controller
        namespace: kube-system
      wellKnownPolicies:
        awsLoadBalancerController: true

addons:
- name: vpc-cni
  version: latest
  tags:
    team: eks
  attachPolicyARNs:
    - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
  resolveConflicts: overwrite
- name: kube-proxy
  version: latest
  tags:
    team: eks
  resolveConflicts: overwrite
- name: coredns
  version: latest
  tags:
    team: eks
  resolveConflicts: overwrite